name = "senarylabs/principia-trust-engine"
version = "0.0.1"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Principia KERI-Cardano Wallet Binding Verification"

[repository]
user = "melshami"
project = "principia-trust-engine"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
